version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DEPENDABOT_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "script/workspace"
    schedule:
      interval: "weekly"
    registries:
      - npm-github
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
